---
title: "Week 6 Study Plan"
weight: 6
bibliography: ../../../../static/libraries.bib
---


<p style="font-size:18px;font-weight:bold;">Week 6</p> 

# Overview

<!-- This week, we will cover the following topics: -->

Continuing on with the Claims Modelling component of the subject, which corresponds to the Section 1 of the CS2 syllabus; In particular, we will cover Module 6--Extreme Value Theory--and

- discuss how to work out the limiting distribution of the maximum of a sample;
- discuss how to work out the limiting distribution of the excess cost of a threshold.


Here is the end of week 5 video, which introduces week 6:

<!--html_preserve-->
<iframe height="420" width="640" allowfullscreen frameborder=0 src="https://echo360.net.au/media/7a7d4ef8-99ba-4ab5-9c7a-075578fa11d2/public?autoplay=false&automute=false"></iframe>
<!--/html_preserve-->

<p style="font-size:10px;color: rgb(252, 156, 249);"> If you wish to watch the embedded videos from Lecture Capture, you need to have logged in and <a href="https://canvas.lms.unimelb.edu.au/courses/150864/external_tools/701">entered Lecture Capture</a> via Canvas once for each session. This is to restrict access to students enrolled at the University of Melbourne only. </p>




See also detailed learning outcomes 1.4 of the CS2 syllabus [``here``](../../0-subject-guide/SILO).





# Main references and lectures


## Module 6

Read: [``Module 6``](../../1-claims-modelling/m6-extreme-value-theory)

Annotate: [``slides``](../../../output/23-GIM-M6-lec.pdf) 
<!-- [``annotated slides``](../../../output/22-GIM-M1-lec_a.pdf) -->

Watch: refer to your lecture recording under "Lecture Capture" ([``UG``](https://canvas.lms.unimelb.edu.au/courses/150824/external_tools/701)/[``PG``](https://canvas.lms.unimelb.edu.au/courses/150864/external_tools/701)). This is where annotated slides will be made available, too.



# Additional preparation and resources

## Mandatory

1. CS2, Unit 4 - Extreme Value Theory (available from Readings Online)
1. @GiKa16 for the R components [``click here to download``](https://doi.org/10.18637/jss.v072.i08)

## Optional

1. n/a



# Tutorials

Note that a full list of exercises is available [``here``](https://canvas.lms.unimelb.edu.au/courses/173733/modules/items/4466801). Please let us know of any mistake or required update on [``Ed``](https://canvas.lms.unimelb.edu.au/courses/173733/external_tools/5601?display=borderless).

## Pre-Tutorial work

Please study those questions **before** the tutorial.

Pre-Tutorial exercises are available in the [``Pre-Tutorial book``](https://canvas.lms.unimelb.edu.au/courses/173733/modules/items/4464391), which already includes solutions. It is recommended to attempt the questions *before* looking at the solutions

## Tutorial materials

Some questions have been especially selected for the tutorials. Students should review and attempt those questions ***prior to their scheduled tutorial***, after they complete the pre-tutorial work. 

The [``Tutorial book``](https://canvas.lms.unimelb.edu.au/courses/173733/modules/items/4464392) includes all questions for the whole semester already, but solutions will only be added sequentially at the end of each week, as we work our way through the set.

Note that solutions will be gradually added to that same document. Hence it is not recommended to print it, as it will regularly change (typos will also dynamically be corrected).

## This week

Friday is a Public Holiday.

For students with a tutorial this week, they can take the opportunity to ask questions in preparation of the mid-semester exam, or tutors may want to catch up on materials.

<!-- Here is the recording available for Week 6 from William: -->

<!-- <!--html_preserve--> -->
<!-- <iframe height="420" width="640" allowfullscreen frameborder=0 src="https://echo360.net.au/media/10b07ac2-01e5-4a94-9493-67d6635fdc3b/public?autoplay=false&automute=false"></iframe> -->
<!-- <!--/html_preserve--> -->

<!-- Here is the recording available for Week 6 from Eric: -->

<!-- <!--html_preserve--> -->
<!-- <iframe height="420" width="640" allowfullscreen frameborder=0 src="https://echo360.net.au/media/e04e8e3c-da0a-4e1e-929c-ee8af0656630/public?autoplay=false&automute=false"></iframe> -->
<!-- <!--/html_preserve--> -->

<!-- <p style="font-size:10px;color: rgb(252, 156, 249);"> If you wish to watch the embedded videos from Lecture Capture, you need to have logged in and <a href="https://canvas.lms.unimelb.edu.au/courses/145406/external_tools/701">entered Lecture Capture</a> via Canvas once for each session. This is to restrict access to students enrolled at the University of Melbourne only. </p> --> -->


## Next week (week 7)

Next week, we will discuss Module 6.

<!-- Note that week 7 will be dedicated to the mid-semester exam. -->


## Additional questions

The "additional questions" are here for reinforcement or revision, but are not the main focus of the tutorials. Solutions for those exercises are already available.


# Preparation for assessment


## Mid-semester (15%) and final (60%) exams

<!-- install.packages("devtools") -->
<!-- devtools::install_github("hadley/emo") -->

- Finalise your summary of Module 5. 


Note that all of Modules 1 to 5 are in scope for the [``mid-semester exam``](../../0-subject-guide/assessment//#mid-semester-exam); that includes tutorials of week 5.

***Make sure you start preparing for the mid-semester exam***

## Assignment (25%)

- Nothing to do for now, except not fall behind with course materials  `r emo::ji("smile")`.


# References